### ISSUE TITLE
Add a way to access all `Expr`s in an `Entity`

### ISSUE THREAD

**Issue by atomb** [dafny-lang/compiler-bootstrap#14]
Currently, the code we have to extract or modify `Expr` fields inside `Entity` values explores all alternatives of the data type each time. It would be useful to have a function to extract all `Expr`s inside an `Entity`, and perhaps a function to map over them, as well, to ensure that later program traversals (such as the one in the auditor) don't miss expressions.

**Comment by cpitclaudel** [comment]
Done in https://github.com/dafny-lang/compiler-bootstrap/commit/0423b75c488f8af91d2088e778fab2d14675b0b6 and https://github.com/dafny-lang/compiler-bootstrap/commit/d5457a843dc858419f93713b3b8d84fea77eea25 , but leaving this issue to open to port the Auditor to use that.
